name: Linter Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  linter-test:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - name: linter
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
      - name: test
        run: yarn test
